name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.7.0
        with:
          hugo-version: '0.124.1' # 修正为您的实际版本 0.124.1
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          external_repository: bitfrost7/bitfrost7.github.io
          publish_branch: master
          publish_dir: ./public
          keep_files: false
          commit_message: ${{ github.event.head_commit.message }}